# AUSF — аутентификация абонента (проверка ключей SIM).
logger:
  level: info

global:
  max:
    ue: 128

ausf:
  sbi:
    server:
      - address: 10.33.0.12
        port: 7777
    client:
      scp:
        - uri: http://10.33.0.11:7777
