# Симулятор базовой станции UERANSIM. Подключается к AMF по SCTP/NGAP.
mcc: '999'
mnc: '70'

nci: '0x000000010'
idLength: 32
tac: 1

linkIp: 10.33.0.30
ngapIp: 10.33.0.30
gtpIp: 10.33.0.30

amfConfigs:
  - address: 10.33.0.20
    port: 38412

slices:
  - sst: 1

ignoreStreamIds: true
