# SCP — прокси сигнального обмена: все NF ходят друг к другу через него.
logger:
  level: info

global:
  max:
    ue: 128

scp:
  sbi:
    server:
      - address: 10.33.0.11
        port: 7777
    client:
      nrf:
        - uri: http://10.33.0.10:7777
