# UDR — хранилище данных абонентов, работает поверх MongoDB.
logger:
  level: info

global:
  max:
    ue: 128

db_uri: mongodb://mongo/open5gs

udr:
  sbi:
    server:
      - address: 10.33.0.14
        port: 7777
    client:
      scp:
        - uri: http://10.33.0.11:7777
